import { test, expect } from "./fixtures"

test("drag, undo, keyboard, save and responsive placements survive navigation", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto("/scene-editor/")
  const sun = page.getByRole("button", { name: "이동: Sun & birds", exact: true })
  await expect(sun).toBeVisible()
  const bounds = (await sun.boundingBox())!
  const y = page.getByRole("spinbutton", { name: "세로 위치 (px)" })
  await expect(y).toHaveValue("78")
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2)
  await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + 72, bounds.y + bounds.height / 2 + 40); await page.mouse.up()
  await expect(y).toHaveValue("118")
  await page.evaluate(() => dispatchEvent(new StorageEvent("storage", { key: "unrelated-setting" })))
  await expect(y).toHaveValue("118")
  await page.getByRole("button", { name: "되돌리기", exact: true }).click()
  await expect(y).toHaveValue("78")
  await page.getByRole("button", { name: "다시 실행", exact: true }).click()
  await expect(y).toHaveValue("118")
  await sun.focus(); await page.keyboard.press("Shift+ArrowDown")
  await expect(y).toHaveValue("128")
  const width = page.getByRole("spinbutton", { name: "너비 (px)" })
  await width.fill("")
  await width.pressSequentially("120")
  await width.press("Enter")
  await expect(width).toHaveValue("120")
  await expect(sun).toHaveCSS("width", "120px")
  await page.getByRole("button", { name: "브라우저에 저장" }).click()
  await page.reload()
  await expect(y).toHaveValue("128")
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole("toolbar")).toContainText("모바일")
  await expect(y).toHaveValue("77")
  await y.fill("95")
  await page.getByRole("button", { name: "브라우저에 저장" }).click()
  await page.getByRole("link", { name: "홈으로" }).click()
  await expect(page.locator(".sun-birds")).toHaveCSS("top", "95px")
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.locator(".sun-birds")).toHaveCSS("top", "128px")
})

test("catalog assets can be placed, layered, deleted, exported and imported", async ({ page }) => {
  await page.goto("/scene-editor/")
  await page.getByRole("searchbox", { name: "파일 검색" }).fill("img/content/11/24.png")
  await page.getByRole("button", { name: "추가: img/content/11/24.png", exact: true }).click()
  await expect(page.locator(".scene-handle")).toHaveCount(12)
  await page.getByRole("checkbox", { name: "본문 위에 배치" }).check()
  await expect(page.locator(".scene-foreground img")).toHaveCount(1)
  await page.getByRole("button", { name: "삭제", exact: true }).click()
  await expect(page.locator(".scene-foreground img")).toHaveCount(0)
  await page.getByRole("button", { name: "되돌리기", exact: true }).click()
  await expect(page.locator(".scene-foreground img")).toHaveCount(1)
  await page.getByText("배치 파일 / 공개 사이트 반영", { exact: true }).click()
  const downloadPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "배치 내보내기" }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe("scene-layout.json")
  await page.getByRole("button", { name: "기본 배치", exact: true }).click()
  await expect(page.locator(".scene-foreground img")).toHaveCount(0)
  await page.getByLabel("배치 파일", { exact: true }).setInputFiles((await download.path())!)
  await expect(page.locator(".scene-foreground img")).toHaveCount(1)
  await page.getByLabel("배치 파일", { exact: true }).setInputFiles({ name: "bad.json", mimeType: "application/json", buffer: Buffer.from('{"version":1,"items":[{"file":"../../bad.png"}]}') })
  await expect(page.getByRole("status").first()).toContainText("올바르지")
  await expect(page.locator(".scene-foreground img")).toHaveCount(1)
})

test("ordinary pages do not download the asset catalog", async ({ page }) => {
  const catalogRequests: string[] = []
  page.on("request", (request) => { if (request.url().includes("catalog.json")) catalogRequests.push(request.url()) })
  await page.goto("/", { waitUntil: "networkidle" })
  expect(catalogRequests).toEqual([])
  await expect(page.locator(".scene-panel")).toHaveCount(0)
})
