import { test, expect } from "./fixtures"

test("background and panel settings persist independently on desktop and mobile", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto("/scene-editor/")
  const set = async (name: string, value: string) => {
    const input = page.getByRole("spinbutton", { name, exact: true })
    await input.fill(value); await input.press("Enter")
  }
  await set("노을 높이 (px)", "350")
  await set("물결 위쪽 위치 (px)", "350")
  await set("물결 높이 (px)", "160")
  await set("물결 무늬 배율 (%)", "200")
  await set("전체 패널 최대 너비 (px)", "1100")
  await set("왼쪽 패널 너비 (px)", "260")
  await set("패널 위쪽 위치 (px)", "520")
  await set("본문 패널 최소 높이 (px)", "1500")
  await expect(page.locator(".sunset-sky")).toHaveCSS("height", "350px")
  await expect(page.locator(".ocean-ripple")).toHaveCSS("background-size", "300px 300px")
  await expect(page.locator(".desk-sidebar")).toHaveCSS("width", "260px")
  await expect(page.locator(".page-sheet")).toHaveCSS("min-height", "1500px")
  await page.getByRole("button", { name: "되돌리기", exact: true }).click()
  await expect(page.locator(".page-sheet")).toHaveCSS("min-height", "0px")
  await page.getByRole("button", { name: "다시 실행", exact: true }).click()
  await page.getByRole("button", { name: "브라우저에 저장", exact: true }).click()
  await page.reload()
  await expect(page.locator(".site-wrap")).toHaveCSS("padding-top", "520px")
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator(".sunset-sky")).toHaveCSS("height", "230px")
  await set("노을 높이 (px)", "190")
  await page.getByRole("button", { name: "브라우저에 저장", exact: true }).click()
  await page.getByRole("link", { name: "홈으로" }).click()
  await expect(page.locator(".sunset-sky")).toHaveCSS("height", "190px")
  await expect(page.locator(".site-wrap")).toHaveCSS("padding-top", "334px")
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.locator(".sunset-sky")).toHaveCSS("height", "350px")
  await expect(page.locator(".site-wrap")).toHaveCSS("max-width", "1100px")
  await page.goto("/scene-editor/")
  await set("전체 패널 최대 너비 (px)", "320")
  const sidebar = (await page.locator(".desk-sidebar").boundingBox())!
  const main = (await page.locator(".page-sheet").boundingBox())!
  expect(main.y).toBeGreaterThan(sidebar.y + sidebar.height)
  expect(main.width).toBe(sidebar.width)
})

test("layout settings survive export and reject malformed imports", async ({ page }) => {
  await page.goto("/scene-editor/")
  const sky = page.getByRole("spinbutton", { name: "노을 높이 (px)", exact: true })
  await sky.fill("410"); await sky.press("Enter")
  await page.getByText("배치 파일 / 공개 사이트 반영", { exact: true }).click()
  const pending = page.waitForEvent("download")
  await page.getByRole("button", { name: "배치 내보내기", exact: true }).click()
  const downloaded = await pending
  await page.getByRole("button", { name: "기본 배치", exact: true }).click()
  await expect(sky).toHaveValue("280")
  await expect(page.getByRole("heading", { name: "에셋 보관함 (2,594)" })).toBeVisible()
  await page.getByLabel("배치 파일", { exact: true }).setInputFiles((await downloaded.path())!)
  await expect(sky).toHaveValue("410")
  await page.getByLabel("배치 파일", { exact: true }).setInputFiles({ name: "bad.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ version: 1, items: [], settings: { desktop: { skyHeight: "0;}body{display:none}" } } })) })
  await expect(page.getByRole("status").first()).toContainText("올바르지")
  await expect(sky).toHaveValue("410")
})

test("drag, undo, keyboard, save and responsive placements survive navigation", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto("/scene-editor/")
  const sun = page.getByRole("button", { name: "이동: Sun & birds", exact: true })
  await expect(sun).toBeVisible()
  const bounds = (await sun.boundingBox())!
  const y = page.getByRole("spinbutton", { name: "세로 위치 (px)", exact: true })
  await expect(y).toHaveValue("78")
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2)
  await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + 72, bounds.y + bounds.height / 2 + 40); await page.mouse.up()
  await expect(y).toHaveValue("118")
  await page.evaluate(() => dispatchEvent(new StorageEvent("storage", { key: "unrelated-setting" })))
  await expect(y).toHaveValue("118")
  await page.getByRole("button", { name: "되돌리기", exact: true }).click()
  await expect(y).toHaveValue("78")
  await page.getByRole("button", { name: "다시 실행", exact: true }).click()
  await expect(y).toHaveValue("118")
  await sun.focus(); await page.keyboard.press("Shift+ArrowDown")
  await expect(y).toHaveValue("128")
  const width = page.getByRole("spinbutton", { name: "너비 (px)", exact: true })
  await width.fill("")
  await width.pressSequentially("120")
  await width.press("Enter")
  await expect(width).toHaveValue("120")
  await expect(sun).toHaveCSS("width", "120px")
  await page.getByRole("button", { name: "브라우저에 저장" }).click()
  await page.reload()
  await expect(y).toHaveValue("128")
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole("toolbar")).toContainText("모바일")
  await expect(y).toHaveValue("77")
  await y.fill("95")
  await page.getByRole("button", { name: "브라우저에 저장" }).click()
  await page.getByRole("link", { name: "홈으로" }).click()
  await expect(page.locator(".sun-birds")).toHaveCSS("top", "95px")
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.locator(".sun-birds")).toHaveCSS("top", "128px")
})

test("catalog assets can be placed, layered, deleted, exported and imported", async ({ page }) => {
  await page.goto("/scene-editor/")
  await page.getByRole("searchbox", { name: "파일 검색" }).fill("img/content/11/24.png")
  await page.getByRole("button", { name: "추가: img/content/11/24.png", exact: true }).click()
  await expect(page.locator(".scene-handle")).toHaveCount(12)
  await page.getByRole("checkbox", { name: "본문 위에 배치" }).check()
  await expect(page.locator(".scene-foreground img")).toHaveCount(1)
  await page.getByRole("button", { name: "삭제", exact: true }).click()
  await expect(page.locator(".scene-foreground img")).toHaveCount(0)
  await page.getByRole("button", { name: "되돌리기", exact: true }).click()
  await expect(page.locator(".scene-foreground img")).toHaveCount(1)
  await page.getByText("배치 파일 / 공개 사이트 반영", { exact: true }).click()
  const downloadPromise = page.waitForEvent("download")
  await page.getByRole("button", { name: "배치 내보내기" }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe("scene-layout.json")
  await page.getByRole("button", { name: "기본 배치", exact: true }).click()
  await expect(page.locator(".scene-foreground img")).toHaveCount(0)
  await page.getByLabel("배치 파일", { exact: true }).setInputFiles((await download.path())!)
  await expect(page.locator(".scene-foreground img")).toHaveCount(1)
  await page.getByLabel("배치 파일", { exact: true }).setInputFiles({ name: "bad.json", mimeType: "application/json", buffer: Buffer.from('{"version":1,"items":[{"file":"../../bad.png"}]}') })
  await expect(page.getByRole("status").first()).toContainText("올바르지")
  await expect(page.locator(".scene-foreground img")).toHaveCount(1)
})

test("ordinary pages do not download the asset catalog", async ({ page }) => {
  const catalogRequests: string[] = []
  page.on("request", (request) => { if (request.url().includes("catalog.json")) catalogRequests.push(request.url()) })
  await page.goto("/", { waitUntil: "networkidle" })
  expect(catalogRequests).toEqual([])
  await expect(page.locator(".scene-panel")).toHaveCount(0)
})
