"use client"

import { motion } from "framer-motion"
import { ArrowLeft, Download, ExternalLink } from "lucide-react"
import Link from "next/link"

export default function PublicationsPage() {
  const publications = [
    {
      title: "Advances in Computer-Generated Holography for 3D Displays",
      journal: "Journal of Optics & Photonics",
      year: 2023,
      authors: "Shin, D.H., Kim, J., Park, S., & Johnson, A.",
      abstract:
        "This paper presents novel algorithms for real-time computer-generated holography that significantly reduce computational complexity while maintaining high image quality. We demonstrate a 5x performance improvement over previous methods, enabling interactive holographic displays on consumer-grade hardware.",
      doi: "10.1088/jopt/2023/12345",
      keywords: ["Computer-generated holography", "Real-time algorithms", "3D displays", "Fourier optics"],
    },
    {
      title: "Metasurface-based Holographic Projections",
      journal: "Nature Photonics",
      year: 2022,
      authors: "Lee, K., Shin, D.H., Wang, L., & Garcia, M.",
      abstract:
        "We demonstrate a novel approach to holographic projection using dielectric metasurfaces. Our design enables high-efficiency, full-color holographic images with wide viewing angles and minimal crosstalk. The fabricated metasurfaces show exceptional performance in both simulated and experimental conditions.",
      doi: "10.1038/nphoton.2022.789",
      keywords: ["Metasurfaces", "Holographic projection", "Nanophotonics", "Dielectric resonators"],
    },
    {
      title: "Real-time Hologram Generation Using Neural Networks",
      journal: "SIGGRAPH Asia",
      year: 2021,
      authors: "Shin, D.H., Zhang, Y., & Miller, R.",
      abstract:
        "This paper introduces a deep learning approach to computer-generated holography that achieves unprecedented speed and quality. Our neural network architecture learns to predict phase patterns directly from target images, bypassing traditional iterative algorithms. We demonstrate real-time performance on consumer GPUs with visual quality comparable to offline methods.",
      doi: "10.1145/3478513.3480499",
      keywords: ["Neural holography", "Deep learning", "Real-time rendering", "Computer-generated holography"],
    },
    {
      title: "Compact Holographic Display Using Polarization-Selective Metasurfaces",
      journal: "Optics Express",
      year: 2021,
      authors: "Shin, D.H., Chen, H., & Williams, T.",
      abstract:
        "We present a novel design for a compact holographic display using polarization-selective metasurfaces. By leveraging the polarization state of light, our system can multiplex multiple holograms in a single optical element, effectively doubling the information density without sacrificing image quality.",
      doi: "10.1364/OE.29.012345",
      keywords: ["Polarization holography", "Metasurfaces", "Compact displays", "Multiplexing"],
    },
    {
      title: "Perceptually-Optimized Phase Retrieval for Holographic Displays",
      journal: "IEEE Transactions on Visualization and Computer Graphics",
      year: 2020,
      authors: "Park, J., Shin, D.H., & Thompson, S.",
      abstract:
        "This paper introduces a perceptually-optimized phase retrieval algorithm for holographic displays. By incorporating models of human visual perception into the optimization process, our method produces holograms that subjectively appear sharper and more contrast-rich than those generated by conventional methods, even with fewer iterations.",
      doi: "10.1109/TVCG.2020.54321",
      keywords: ["Phase retrieval", "Perceptual optimization", "Holographic displays", "Visual perception"],
    },
  ]

  return (
    <div className="container mx-auto px-4">
      <Link href="/" className="inline-flex items-center text-indigo-400 hover:text-indigo-300 mb-8 transition-colors">
        <ArrowLeft className="h-4 w-4 mr-2" />
        Back to Home
      </Link>

      <motion.div
        className="max-w-4xl mx-auto"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <motion.h1
          className="text-4xl font-light text-white mb-8 tracking-tight"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.2, duration: 0.5 }}
        >
          Publications
        </motion.h1>

        <div className="space-y-6">
          {publications.map((pub, index) => (
            <motion.div
              key={pub.title}
              className="bg-black/30 backdrop-blur-md border border-white/10 rounded-xl p-6"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 + index * 0.1, duration: 0.5 }}
            >
              <h2 className="text-xl font-medium text-white mb-2">{pub.title}</h2>
              <p className="text-indigo-400 mb-2">
                {pub.journal}, {pub.year}
              </p>
              <p className="text-white/70 mb-4 italic">{pub.authors}</p>

              <p className="text-white/80 mb-4 leading-relaxed">{pub.abstract}</p>

              <div className="flex flex-wrap gap-2 mb-4">
                {pub.keywords.map((keyword, i) => (
                  <span key={i} className="bg-indigo-900/30 text-indigo-300 text-xs px-2 py-1 rounded-full">
                    {keyword}
                  </span>
                ))}
              </div>

              <div className="flex items-center space-x-4 text-sm">
                <a
                  href={`https://doi.org/${pub.doi}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-indigo-400 hover:text-indigo-300 flex items-center transition-colors"
                >
                  <ExternalLink className="h-4 w-4 mr-1" />
                  DOI: {pub.doi}
                </a>
                <a href="#" className="text-indigo-400 hover:text-indigo-300 flex items-center transition-colors">
                  <Download className="h-4 w-4 mr-1" />
                  Download PDF
                </a>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </div>
  )
}
